# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'pocksquash:$(build.buildId)'

steps:
- script: |
        az login --service-principal -u $(spname) -p $(pswd) --tenant "alastaidoutlook.onmicrosoft.com"
        az acr login -n $(dockerId) -u $(spname) -p $(pswd) 
        az acr build -r $(dockerId) -f Dockerfile.ARM --image $(imageName)arm .
        docker build -f Dockerfile -t $(dockerId).azurecr.io/$(imageName)x86 .
        #docker login -u $(spname) -p $(pswd) $(dockerid).azurecr.io
        docker push $(dockerId).azurecr.io/$(imageName)x86
